############################################################################
# 原則 http://jekyllrb.com/docs/configuration/#default-configuration からの
# 差分のみ記述している。記述順序も前述に従う。

### Handling Reading
exclude:
  - 'README.md'
  - 'tmp'

# デフォルトと同じだが「utf-8で記事を書こう」という宣言的な意味合で残した。
encoding: utf-8

### Filtering Content
future: true

### Plugins
gems:
  #- jekyll-redirect-from

### Outputting
permalink: pretty

### Markdown Processors
kramdown:
  input: GFM
