name: CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: cedrickring/golang-action@1.3.0
    - name: Golang Action
      run: |
        go get -u github.com/koron/go-github
        go get -u gopkg.in/yaml.v2
        go run _scripts/vim_jp-redirects-update/main.go
  
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
